name = "Contourlets"
uuid = "4d443f37-8914-48d3-9d0d-9e555eaf7273"
version = "0.1.0"
authors = ["Contourlets.jl Contributors"]

[workspace]
projects = ["test", "docs", "benchmark"]

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[weakdeps]
GPUArrays = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"

[extensions]
ContourletsGPUExt = ["GPUArrays", "KernelAbstractions"]

[compat]
FFTW = "1"
GPUArrays = "10, 11"
KernelAbstractions = "0.9"
LinearAlgebra = "1"
PrecompileTools = "1"
julia = "1.10"
